plug and test feature
sdgtt/nebula pull request #114
Opened 2024-04-16 04:04 UTC by tagoylo

2024-05-24 02:58 UTC, kimpaller requested changes

2024-05-24 02:58 UTC, kimpaller commented on nebula/network.py
> +        descriptor_path = "nebula/resources/kuiper.json"
Since this file resides in the host  (can be Windows) where nebula is installed, i suggest referring to this file in an os-agnostic and relative manner just like this example

https://github.com/sdgtt/nebula/blob/fe553ffe7eea2ceaaf6bb8f4e9118e704dfeb7a6/nebula/helper.py#L86

2024-05-24 02:58 UTC, kimpaller commented on nebula/network.py
> +            os.replace("kuiper.json", descriptor_path)
Does os.replace copy "kuiper.json" to descriptor_path? Why not just set the descriptor_path="kuiper.json" directly?

2024-05-24 02:58 UTC, kimpaller commented on nebula/tasks.py
> +    sdcard=False,
I suggest adding this argument to the last part, just to make sure no existing call to this function that does not specify argument to break.

```
def update_boot_files_jtag_manager(
    c,
    system_top_bit_path="system_top.bit",
    bootbinpath="BOOT.BIN",
    uimagepath="uImage",
    devtreepath="devicetree.dtb",
    folder=None,
    yamlfilename="/etc/default/nebula",
    board_name=None,
    sdcard=False,
)
```

2024-05-24 02:58 UTC, kimpaller commented on nebula/tasks.py
> +        "sdcard": "Get boot files from the sdcard",
Please consider argument placement ordering as commented above.

2024-05-24 02:58 UTC, kimpaller commented on nebula/usbmux.py
> +            descriptor_path = "nebula/resources/kuiper.json"
Is it possible to add descriptor_path as argument instead to the update_boot_files_from_sdcard_itself() function? this makes this method more reconfigurable

2024-05-24 02:58 UTC, kimpaller commented on nebula/usbmux.py
> +        args_filtered = dict(filter(lambda item: item[1] is not None, args.items()))
cool 😎

2024-05-24 02:58 UTC, kimpaller commented on tests/test_network.py
> +
Might be good to also add test for the usbmux.py mods 😅

2024-05-24 10:14 UTC, jpineda3 reviewed
I agree with Kim's comments.

2024-05-24 10:14 UTC, jpineda3 commented on nebula/usbmux.py
> +                if "tmp" in bootfile_loc:
What case will have "tmp" in the bootfile path and vice versa?

2024-06-04 06:25 UTC, tagoylo commented on nebula/tasks.py
> +    sdcard=False,
c3d9abe

2024-06-04 06:25 UTC, tagoylo commented on nebula/tasks.py
> +        "sdcard": "Get boot files from the sdcard",
c3d9abe

2024-06-04 07:39 UTC, tagoylo commented on nebula/helper.py
> +            projects = filter(partial(project_filter, filters=filter_dict), projects)
The result is still a list that matches the filter_dict, thus looping is still necessary. Need to double check with Kim.

2024-06-05 04:21 UTC, tagoylo commented on nebula/network.py
> +        descriptor_path = "nebula/resources/kuiper.json"
b2bcf5c

2024-06-05 04:21 UTC, tagoylo commented on nebula/usbmux.py
> +            descriptor_path = "nebula/resources/kuiper.json"
b2bcf5c

2024-06-05 05:04 UTC, tagoylo commented on nebula/network.py
> +            os.replace("kuiper.json", descriptor_path)
This updates the kuiper.json under resources to have the same content from the kuiper.json of the sd card/target. But yes, I'll check if it would behave the same if directly setting the descriptor_path to kuiper.json.

2024-06-05 08:00 UTC, tagoylo commented on tests/test_network.py
> +
93e5225

2024-06-06 06:07 UTC, tagoylo commented on nebula/network.py
> +            os.replace("kuiper.json", descriptor_path)
c9bd53e

2024-07-15 01:06 UTC, kimpaller approved these changes

2024-07-15 01:33 UTC, jpineda3 approved these changes

2024-07-15 01:43 UTC, merged